version: '3.8'

services:
  chat:
    build: .
    restart: always
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - SECRET_KEY=${SECRET_KEY}
    command: >
      gunicorn
      --worker-class eventlet
      --workers 1
      --bind 0.0.0.0:8000
      --log-level info
      --access-logfile -
      --error-logfile -
      wsgi:app
    networks:
      - chat_network

  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN=${DOMAIN}
    depends_on:
      - chat
    networks:
      - chat_network

volumes:
  caddy_data:
  caddy_config:

networks:
  chat_network:
    driver: bridge