version: '3.8'

services:
  chat:
    build: .
    restart: always
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - GUNICORN_WORKERS=${GUNICORN_WORKERS}
      - GUNICORN_WORKER_CLASS=${GUNICORN_WORKER_CLASS}
      - GUNICORN_HOST=${GUNICORN_HOST}
      - GUNICORN_PORT=${GUNICORN_PORT}
    command: >
      gunicorn
      --worker-class ${GUNICORN_WORKER_CLASS}
      --workers ${GUNICORN_WORKERS}
      --bind ${GUNICORN_HOST}:${GUNICORN_PORT}
      --log-level info
      --access-logfile -
      --error-logfile -
      app:app
    networks:
      - chat_network

  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN=${DOMAIN}
    depends_on:
      - chat
    networks:
      - chat_network

volumes:
  caddy_data:
  caddy_config:

networks:
  chat_network:
    driver: bridge